
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    name: test
    url: jdbc:mysql://www.mlnode.com:3306/antifake?useUnicode=true&characterEncoding=UTF-8
    username: mltech
    password: Itelly0u
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #redis配置
  redis:
     host: www.mlnode.com
     database: 0
     password: 
     port: 6379
     timeout: 30000 
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.antifake.model
 